### ISSUE TITLE
URL in multisite with domainmapping

### ISSUE THREAD

**Issue by lupa18** [gutobenn/wp-to-diaspora#112]
Hello ! in a mu site with domainmapping plugin, the URL posted on diaspora isn't what we want. 

For example, the URL mapped is: http://www.tedic.org/global-cyber-space-conference-2015/

and URL in diasp looks like:  http://principal.blog.tedic.org/global-cyber-space-conference-2015/ (the original and unmapped URL)

see image: 

![seleccion_163](https://cloud.githubusercontent.com/assets/463429/10808279/20d9dd78-7dc8-11e5-8e5f-035f1bb40b21.png)

**Comment by noplanman** [comment]
Am I correct to assume that the domain mapping plugin you are using is [WordPress MU Domain Mapping](https://wordpress.org/plugins/wordpress-mu-domain-mapping/)?

I found this support forum entry, maybe it solves your problem:
https://wordpress.org/support/topic/links-inside-mapped-site-show-subdomain

If not, please let us know and we'll find a solution :blush:

**Comment by lupa18** [comment]
Works fine !! Then one more question, as you can see in image, language is mixed. Since most parts are in Spanish, "Originally posted..." is in English, and the same happen inside wordpress with this plugin. Should I open a new issue?

**Comment by noplanman** [comment]
@lupa18 Great to hear that the forum post fixed it!

About the language, the problem is that the Spanish translations of the plugin isn't complete. I'm really hoping to get a friend of mine to help with that next week.

Alternatively, for the moment, you could add a filter to change the text:
```php
add_filter( 'wp2d_posted_at_link_filter',
            function( $default, $text, $permalink, $title ) {
                $text = 'Originally posted at:';
                return sprintf( '%1$s <a href="%2$s" title="%3$s">%2$s</a>',
                    $text, $permalink, $title );
            }, 10, 4 );
```
You can add this snippet to your `functions.php` file and simply change the `Originally posted at:` text to whatever you like :wink: 

No need to open a new ticket, we're on it!

**Comment by lupa18** [comment]
We also could help in translate it ... write us on lupa at tedic.org with some instructions and could help
