### ISSUE TITLE
Prepopulated list of pods

### ISSUE THREAD

**Issue by noplanman** [gutobenn/wp-to-diaspora#16]
Add a list of existing pods to make the pod selection easier for the user.
The possibility to enter a custom pod name should still remain!

**Comment by ciubotaru** [comment]
Let me tell how I solved the same problem in the [Share on Diaspora*](https://github.com/ciubotaru/share-on-diaspora) plugin.

* The user can manually enter his/her pod.
* There is a pre-populated list. It consists of one pod, `example.com`. Any real list is temporary, because pods come and go. `example.com` is shown only when nothing else works.
* There is a button to download a fresh list from `podupti.me`.
* There is a button to connect a small auxiliary plugin, [Diaspora Podlist Updater](https://github.com/ciubotaru/diaspora-podlist-updater), which once a day automatically downloads the fresh list.

There's also some usability "sugar", like autocompletion (based on the list), textfield placeholder (random pod from the list, or `example.com` if there's no list).

**Comment by noplanman** [comment]
Thanks so much for the ideas!
I've already been thinking along the line of getting the podupti.me list somehow, but haven't yet explored it further. Knowing that it's a simple fetch is really great to know :-)

I like the approach of having a dedicated mini-plugin for the list updating, which allows other plugins to tap into the list more resource-friendly. Thing is, more often than not, only one update is required for the initial setup. After selecting the correct pod, it rarely gets changed I think.

As soon as I tackle this issue, I will put more brain work into it and come up with something that makes sense all round :-D

**Comment by gutobenn** [comment]
Closed via 28054c41397631e048e9090f556c44668c113ab2 and 1352eb800786938fca3b16140210f77b0fcd0edb.
Thanks! :)
