### ISSUE TITLE
After update: Couldn't connect to .... Login failed.

### ISSUE THREAD

**Issue by schnied** [gutobenn/wp-to-diaspora#46]
hi, 

in the meantime, this plugin works fine for me. after the last update (i think), the only message i got is:

Couldn't connect to "https://pod.sd.vc": Login failed.

any idea? how can i debug this? 

regards
stefan

**Comment by noplanman** [comment]
Hi stefan!

Thanks for your message, we are aware of the problem and have released 1.3.1 a moment ago.

Please try it and see if it works for you.

On the WP to diaspora* settings page, you can add `&debugging` at the end of the URL to get some basic debug output at the top of the page. If you still have issues, simply copy and paste the debug text into your next comment so that we can see where the error happens.

See you!

**Comment by schnied** [comment]
heyho... yeah! now it works (again)!
i will try the debug function next time when it doesn't work... but i hope that i don't need to ;-)
thanks you.
stefan

**Comment by noplanman** [comment]
Wonderful, great to hear that it's all up and running again.
If you have any other issues or questions don't hesitate to write :-)
